name: log4cats-mtl
baseurl: /log4cats-mtl
description: Log4cats MTL Integration Layer
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0
org: io.chrisdavenport
markdown: kramdown
